name: Check

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      - name: "Install `cargo-deny`"
        run: "cargo binstall -y cargo-deny"
      - name: "`cargo deny`"
        run: cargo deny check
      - name: "`cargo check`"
        run: cargo check --all-targets --all-features
      - name: "`cargo clippy`"
        run: cargo clippy --workspace --all-targets --all-features
      - name: "`cargo test`"
        run: cargo test
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: binary
          path: target/release/brie(|ctl)
